version: '3'

volumes:
  share_data: {}
  kernel: {}

services:
  ros2:
    image: how2flow/ros2:foxy
    container_name: ros2-foxy
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - share_data:/var/lib/share_data
    environment:
      - PYTHONUNBUFFERED=0

# docker compose up -d
# docker attach robot_ws
