#!/bin/bash

apt-get update && apt-get install -y --no-install-recommends \
  software-properties-common \
  locales

add-apt-repository universe

locale-gen en_US en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
locale

apt-get update && apt-get install -y --no-install-recommends \
  curl \
  gnupg2 \
  locales \
  lsb-release

curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
  -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
  http://packages.ros.org/ros2/ubuntu focal main" \
  | tee /etc/apt/sources.list.d/ros2.list > /dev/null

apt-get update && apt-get install -y --no-install-recommends \
  ros-foxy-desktop \
  ros-foxy-rmw-cyclonedds* \
  ros-foxy-rmw-fastrtps*
