name: 'docker ros2 foxy (CI/CD)'

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - "README.md"
      - "docker/foxy/docker-compose.yaml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/Checkout@v3

      - name: 'Docker upload'
        uses: how2flow/upload-docker-action@v1
        with:
          context: ./docker/latest
          repository: 'ros2'
          release: 'foxy'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
